// @vitest-environment happy-dom

import { describe, expect, it } from 'vitest'

import { useChatTextRendering } from './useChatTextRendering'
import { buildShareDom } from './useChatShareExport'

describe('buildShareDom protocol-shaped documentation', () => {
  it('clones the complete rendered message into the share image stage', () => {
    const text = [
      'Document `<tool_calls>` inline.',
      '```xml',
      '<tool_calls><invoke name="demo"></invoke></tool_calls>',
      '```',
      'Keep `<｜DSML｜tool_calls>` too.',
      '<details><summary>View areas around line 10</summary>Visible note.</details>',
      'Final suffix.',
    ].join('\n')
    const source = document.createElement('article')
    source.className = 'msg msg-ai'
    source.dataset.shareMessageId = 'assistant-literal'
    const body = document.createElement('div')
    body.className = 'msg-body'
    body.innerHTML = useChatTextRendering().renderMarkdown(text)
    source.appendChild(body)

    const stage = buildShareDom([source])
    const sharedText = stage.querySelector('.msg-body')?.textContent || ''

    expect(sharedText).toContain('<tool_calls>')
    expect(sharedText).toContain('<｜DSML｜tool_calls>')
    expect(sharedText).toContain('Visible note.')
    expect(sharedText).toContain('Final suffix.')
  })

  it('records the localized AI provenance label for the rendered PNG footer', () => {
    const source = document.createElement('article')
    source.dataset.shareMessageId = 'assistant-provenance'

    const stage = buildShareDom(
      [source],
      'light',
      'Content generated by AI, for reference only.',
    )
    const metrics = JSON.parse(stage.dataset.shareTemplateMetrics || '{}')

    expect(metrics.disclaimer).toBe('Content generated by AI, for reference only.')
  })

  it('removes tool timeline controls from the static share image', () => {
    const source = document.createElement('article')
    source.dataset.shareMessageId = 'assistant-tools'
    const toolbar = document.createElement('div')
    toolbar.className = 'tool-timeline__toolbar'
    toolbar.setAttribute('data-share-control', '')
    toolbar.innerHTML = '<span>3 calls</span><button type="button">Collapse all</button>'
    const toolResult = document.createElement('div')
    toolResult.className = 'tool-row-body'
    toolResult.textContent = 'tool output'
    source.append(toolbar, toolResult)

    const stage = buildShareDom([source])

    expect(stage.querySelector('.tool-timeline__toolbar')).toBeNull()
    expect(stage.querySelector('.tool-row-body')?.textContent).toBe('tool output')
  })

  it('omits collapsed execution activity while keeping the canonical answer', () => {
    const source = document.createElement('article')
    source.dataset.shareMessageId = 'assistant-activity'
    const activity = document.createElement('details')
    activity.className = 'assistant-activity'
    activity.innerHTML = [
      '<summary class="assistant-activity__summary">Activity · 2 steps</summary>',
      '<div class="assistant-activity__body">',
      '<div>Private path: /Users/example/project</div>',
      '<div>Tool error: secret diagnostic</div>',
      '</div>',
    ].join('')
    const answer = document.createElement('div')
    answer.className = 'msg-ai-text'
    answer.textContent = 'Canonical answer'
    source.append(activity, answer)

    const stage = buildShareDom([source])

    expect(stage.querySelector('.assistant-activity')).toBeNull()
    expect(stage.textContent).toContain('Canonical answer')
    expect(stage.textContent).not.toContain('/Users/example/project')
    expect(stage.textContent).not.toContain('secret diagnostic')
  })

  it('preserves explicitly expanded activity as a structured static block', () => {
    const source = document.createElement('article')
    source.dataset.shareMessageId = 'assistant-expanded-activity'
    const activity = document.createElement('details')
    activity.className = 'assistant-activity'
    activity.setAttribute('open', '')
    activity.innerHTML = [
      '<summary class="assistant-activity__summary">Activity · 2 steps</summary>',
      '<div class="assistant-activity__body">',
      '<section class="thinking-block">Checked the evidence.</section>',
      '<div class="step-card"><div class="tool-row-body">Tool output</div></div>',
      '</div>',
    ].join('')
    const answer = document.createElement('div')
    answer.className = 'msg-ai-text'
    answer.textContent = 'Canonical answer'
    source.append(activity, answer)

    const stage = buildShareDom([source])

    expect(stage.querySelector('.assistant-activity')).toBeNull()
    expect(stage.querySelector('.chat-share-export-activity')).not.toBeNull()
    expect(stage.querySelector('.chat-share-export-activity__label')?.textContent)
      .toBe('Activity · 2 steps')
    expect(stage.querySelector('.thinking-block')?.textContent).toBe('Checked the evidence.')
    expect(stage.querySelector('.tool-row-body')?.textContent).toBe('Tool output')
    expect(stage.textContent?.match(/Canonical answer/g)).toHaveLength(1)
  })
})
