"""Gateway RPC public-surface baseline tests for architecture refactors."""

from __future__ import annotations

from opensquilla.gateway.rpc import get_dispatcher

EXPECTED_RPC_METHOD_SCOPES = {
    "agent": "operator.write",
    "agent.identity.get": "operator.read",
    "agent.wait": "operator.write",
    "agents.create": "operator.admin",
    "agents.delete": "operator.admin",
    "agents.files.get": "operator.read",
    "agents.files.list": "operator.read",
    "agents.files.set": "operator.admin",
    "agents.list": "operator.read",
    "agents.update": "operator.admin",
    "channels.logout": "operator.admin",
    "channels.restart": "operator.admin",
    "channels.status": "operator.read",
    "chat.abort": "operator.write",
    "chat.history": "operator.read",
    "chat.inject": "operator.admin",
    "chat.send": "operator.write",
    "commands.list_for_surface": "operator.read",
    "config.apply": "operator.admin",
    "config.get": "operator.read",
    "config.patch": "operator.admin",
    "config.patch.safe": "operator.write",
    "config.schema": "operator.admin",
    "config.schema.lookup": "operator.read",
    "config.set": "operator.admin",
    "cron.add": "operator.admin",
    "cron.create": "operator.admin",
    "cron.list": "operator.read",
    "cron.remove": "operator.admin",
    "cron.run": "operator.admin",
    "cron.runs": "operator.read",
    "cron.status": "operator.read",
    "cron.subscribe": "operator.read",
    "cron.unsubscribe": "operator.read",
    "cron.update": "operator.admin",
    "diagnostics.set": "operator.admin",
    "diagnostics.status": "operator.read",
    "doctor.memory.status": "operator.read",
    "exec.approval.forget": "operator.approvals",
    "exec.approval.request": "operator.approvals",
    "exec.approval.resolve": "operator.approvals",
    "exec.approval.snapshot": "operator.approvals",
    "exec.approval.waitDecision": "operator.approvals",
    "exec.approvals.get": "operator.approvals",
    "exec.approvals.node.get": "operator.admin",
    "exec.approvals.node.set": "operator.admin",
    "exec.approvals.set": "operator.approvals",
    "gateway.identity.get": "operator.read",
    "health": "operator.read",
    "last-heartbeat": "operator.read",
    "logs.status": "operator.read",
    "logs.tail": "operator.read",
    "logs.trace": "operator.read",
    "memory.list": "operator.read",
    "memory.search": "operator.read",
    "memory.show": "operator.read",
    "models.list": "operator.read",
    "onboarding.catalog": "operator.read",
    "onboarding.channel.disable": "operator.admin",
    "onboarding.channel.enable": "operator.admin",
    "onboarding.channel.probe": "operator.admin",
    "onboarding.channel.remove": "operator.admin",
    "onboarding.channel.upsert": "operator.admin",
    "onboarding.imageGeneration.configure": "operator.admin",
    "onboarding.memory_embedding.configure": "operator.admin",
    "onboarding.provider.configure": "operator.admin",
    "onboarding.router.catalog": "operator.read",
    "onboarding.router.configure": "operator.admin",
    "onboarding.search.configure": "operator.admin",
    "onboarding.status": "operator.read",
    "plugin.approval.request": "operator.approvals",
    "plugin.approval.resolve": "operator.approvals",
    "plugin.approval.waitDecision": "operator.approvals",
    "providers.status": "operator.read",
    "search.query": "operator.write",
    "search.status": "operator.read",
    "secrets.reload": "operator.admin",
    "secrets.resolve": "operator.admin",
    "send": "operator.write",
    "sessions.abort": "operator.write",
    "sessions.compact": "operator.write",
    "sessions.contextCompact": "operator.write",
    "sessions.create": "operator.write",
    "sessions.delete": "operator.admin",
    "sessions.get": "operator.read",
    "sessions.list": "operator.read",
    "sessions.messages.subscribe": "operator.read",
    "sessions.messages.unsubscribe": "operator.read",
    "sessions.patch": "operator.admin",
    "sessions.preview": "operator.read",
    "sessions.reset": "operator.write",
    "sessions.resolve": "operator.read",
    "sessions.send": "operator.write",
    "sessions.subscribe": "operator.read",
    "sessions.unsubscribe": "operator.read",
    "set-heartbeats": "operator.admin",
    "skills.bins": "node",
    "skills.deps.install": "operator.admin",
    "skills.get": "operator.read",
    "skills.install": "operator.admin",
    "skills.list": "operator.read",
    "skills.search": "operator.read",
    "skills.status": "operator.read",
    "skills.uninstall": "operator.admin",
    "skills.update": "operator.admin",
    "status": "operator.read",
    "system-event": "operator.admin",
    "system-presence": "operator.read",
    "tools.catalog": "operator.read",
    "tools.effective": "operator.read",
    "tools.search_provider": "operator.read",
    "usage.cost": "operator.read",
    "usage.status": "operator.read",
    "wake": "operator.write",
    "wizard.cancel": "operator.admin",
    "wizard.next": "operator.admin",
    "wizard.start": "operator.admin",
    "wizard.status": "operator.admin",
}


def test_rpc_method_surface_and_scopes_are_stable() -> None:
    registry = get_dispatcher()
    actual = {
        method: registry.get_entry(method).required_scope
        for method in registry.methods()
        if registry.get_entry(method) is not None
    }

    assert actual == EXPECTED_RPC_METHOD_SCOPES
