#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: scripts/refactor_stage_init.sh SLICE_SLUG [BRANCH_NAME] [WORKTREE_PATH]

Create a stage-plan file from docs/refactor/stage-template.md and print the
recommended child worktree command. This script does not create the worktree.

Example:
  scripts/refactor_stage_init.sh cli-chat-workflows
USAGE
}

if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
  usage
  exit 0
fi

slice="${1:-}"
if [[ -z "$slice" ]]; then
  usage >&2
  exit 2
fi

branch="${2:-codex/refactor-$slice}"
worktree="${3:-../opensquilla-refactor-$slice}"

root="$(git rev-parse --show-toplevel)"
cd "$root"

template="docs/refactor/stage-template.md"
if [[ ! -f "$template" ]]; then
  echo "ERROR: missing $template" >&2
  exit 1
fi

date="$(date +%Y-%m-%d)"
stage_dir="docs/refactor/stages"
stage_file="$stage_dir/$date-$slice.md"
mkdir -p "$stage_dir"

if [[ -e "$stage_file" ]]; then
  echo "ERROR: stage file already exists: $stage_file" >&2
  exit 1
fi

{
  echo "<!-- Generated by scripts/refactor_stage_init.sh. Fill this plan before implementation. -->"
  echo
  sed \
    -e "s/^- Name:$/- Name: $slice/" \
    -e "s/^- Date:$/- Date: $date/" \
    -e "s|^- Child branch:$|- Child branch: \`$branch\`|" \
    -e "s|^- Child worktree:$|- Child worktree: \`$worktree\`|" \
    "$template"
} > "$stage_file"

echo "Created $stage_file"
echo
echo "Recommended next command:"
echo "git worktree add $worktree -b $branch"
echo
echo "Required before code changes:"
echo "- Run scripts/refactor_preflight.sh --allow-dirty"
echo "- Use superpowers:writing-plans"
echo "- Use superpowers:test-driven-development for code or executable behavior"
