"""Shared CLI compatibility facade for local path and attachment commands."""

from __future__ import annotations

from opensquilla.cli.attachment_files import (
    CLI_ALLOWED_FILE_MIMES,
    CLI_ENGINE_ATTACHMENT_BYTES,
    CLI_IMAGE_ATTACHMENT_BYTES,
    CLI_IMAGE_MIMES,
    CLI_INLINE_THRESHOLD_BYTES,
    CLI_STAGED_PDF_BYTES,
    CLI_TEXT_ATTACHMENT_BYTES,
    CLI_TEXT_FAMILY_MIMES,
    AsyncUploadCallable,
    UploadCallable,
    _allowed_label,
    _can_stage_mime,
    _check_size_policy,
    _ensure_existing_file,
    _inline_attachment,
    async_file_prompt_and_attachments,
    attachment_size_limit_for_mime,
    attachments_from_paths,
    build_file_attachment,
    build_file_attachment_async,
    file_prompt_and_attachments,
    image_prompt_and_attachments,
    image_prompt_from_command,
    mime_for_path,
)
from opensquilla.cli.attachment_paths import (
    PATH_IMAGE_BINARY_EXTENSIONS,
    PATH_OBVIOUS_BINARY_EXTENSIONS,
    PATH_REMOTE_GATEWAY_MESSAGE,
    PATH_SPREADSHEET_EXTENSIONS,
    PATH_TEXT_EXTENSIONS,
    parse_path_command,
    path_prompt_and_attachments,
    path_strategy_hint,
)

_ATTACHMENT_PRIVATE_COMPAT_ALIASES = (
    _allowed_label,
    _can_stage_mime,
    _check_size_policy,
    _ensure_existing_file,
    _inline_attachment,
)

__all__ = (
    "AsyncUploadCallable",
    "CLI_ALLOWED_FILE_MIMES",
    "CLI_ENGINE_ATTACHMENT_BYTES",
    "CLI_IMAGE_ATTACHMENT_BYTES",
    "CLI_IMAGE_MIMES",
    "CLI_INLINE_THRESHOLD_BYTES",
    "CLI_STAGED_PDF_BYTES",
    "CLI_TEXT_ATTACHMENT_BYTES",
    "CLI_TEXT_FAMILY_MIMES",
    "PATH_IMAGE_BINARY_EXTENSIONS",
    "PATH_OBVIOUS_BINARY_EXTENSIONS",
    "PATH_REMOTE_GATEWAY_MESSAGE",
    "PATH_SPREADSHEET_EXTENSIONS",
    "PATH_TEXT_EXTENSIONS",
    "UploadCallable",
    "async_file_prompt_and_attachments",
    "attachment_size_limit_for_mime",
    "attachments_from_paths",
    "build_file_attachment",
    "build_file_attachment_async",
    "file_prompt_and_attachments",
    "image_prompt_and_attachments",
    "image_prompt_from_command",
    "mime_for_path",
    "parse_path_command",
    "path_prompt_and_attachments",
    "path_strategy_hint",
)
